# Generated by Django 4.2.8 on 2024-01-04 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("EMOTION_OPTION_1", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_2", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_3", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_4", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_5", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_6", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_7", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_8", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_9", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_10", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_11", models.CharField(max_length=50, null=True)),
                ("EMOTION_OPTION_12", models.CharField(max_length=50, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lyrics", models.CharField(max_length=60)),
                ("content", models.TextField(max_length=150)),
                ("title", models.CharField(max_length=200)),
                ("singer", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200, null=True)),
                (
                    "sings_emotion",
                    models.CharField(
                        choices=[
                            ("쾌감", "쾌감"),
                            ("벅참", "벅참"),
                            ("신남", "신남"),
                            ("행복", "행복"),
                            ("희망", "희망"),
                            ("설렘", "설렘"),
                            ("평온", "평온"),
                            ("위로", "위로"),
                            ("센치함", "센치함"),
                            ("쓸쓸함", "쓸쓸함"),
                            ("그리움", "그리움"),
                            ("슬픔", "슬픔"),
                        ],
                        max_length=50,
                    ),
                ),
                ("likes_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scrap",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scraped_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
