# Generated by Django 4.2.8 on 2024-01-04 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_com_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="com_count",
        ),
    ]
