# Generated by Django 3.2.8 on 2024-01-06 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_remove_post_com_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_11',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_12',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMOTION_OPTION_9',
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('emo_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.IntegerField(choices=[(1, '쾌감'), (2, '벅참'), (3, '신남'), (4, '행복'), (5, '희망'), (6, '설렘'), (7, '평온'), (8, '위로'), (9, '센치함'), (10, '쓸쓸함'), (11, '그리움'), (12, '슬픔')])),
                ('emo_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emo_post', to='posts.post')),
                ('emo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emo_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
