# Generated by Django 5.0.1 on 2024-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_emotion_content_alter_post_sings_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='lyrics',
            field=models.CharField(max_length=200),
        ),
    ]
