# Generated by Django 5.0.1 on 2024-01-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_content_alter_post_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
