# Generated by Django 5.0.1 on 2024-02-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_com_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='liked_by_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
