# Generated by Django 5.0.1 on 2024-02-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_liked_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked_by_user',
        ),
    ]
