# Generated by Django 5.0.1 on 2024-01-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_useremotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmotion',
        ),
    ]
