# Generated by Django 4.2.8 on 2024-01-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, choices=[('cd', 'cd'), ('mic', 'mic'), ('headset', 'headset')], max_length=7, null=True),
        ),
    ]
