# Generated by Django 5.0.1 on 2024-01-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='report',
        ),
    ]
