# Generated by Django 5.0.1 on 2024-01-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.IntegerField(blank=True, choices=[(1, 'chicken'), (2, 'cat'), (3, 'dog'), (4, 'horse')], null=True),
        ),
    ]
