# Generated by Django 3.2.8 on 2024-03-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recomlist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
