# Generated by Django 3.2.8 on 2024-01-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_remove_post_com_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sings_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sings_post', to='posts.post')),
            ],
        ),
    ]
