# Generated by Django 3.2.8 on 2024-01-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_com_count'),
        ('sings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sings',
            name='sings_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sings_posts', to='posts.post'),
        ),
    ]
